config/routes.rb
Rails.application.routes.draw do
  resources :banks
  resources :agencies
  resources :accounts
  resources :operations

  get 'home/index'
  root to: 'home#index'
  devise_for :users

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  belongs_to :bank
  has_many :accounts

  validates_presence_of :bank_id, :ag_number

  def number_with_bank
    "#{ag_number} (#{bank.bank_name})"
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:bank_id, :ag_name, :ag_number, :ag_address)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.slim
.container style=("margin-top: 50px;")
  = form_for @agency do |f|
    -if @agency.errors.any?
      #error_explanation
        h2 = "#{pluralize(@agency.errors.count, "error")} prohibited this agency from being saved:"
        ul
          - @agency.errors.full_messages.each do |msg|
            li= msg

    .form-group
      = f.label :bank_name
      = collection_select :agency, :bank_id, Bank.all, :id, :name_with_number

    .form-group
      = f.label "Agency Name"
      = f.text_field :ag_name

    .form-group
      = f.label "Agency Number"
      = f.text_field :ag_number

    .form-group
      = f.label "Agency Address"
      = f.text_field :ag_address

    .actions
      = f.submit 'Save'

app/views/agencies/edit.html.slim
h1 Editing agency

== render 'form'

= link_to 'Show', @agency
'|
= link_to 'Back', agencies_path

app/views/agencies/index.html.slim
div.agencies
  h1.agencies
    | Listing currently registered agencies

  button.btn.btn-dark.btn-lg.active
    = link_to 'Register a new Agency', new_agency_path

  table.table.table-striped.table-hover
    thead.thead-dark
      tr
        th.agencies
          | Bank
        th.agencies
          | Agency Name
        th.agencies
          | Agency Number
        th.agencies
          | Agency Address
        th
        th
        th

    tbody
      - @agencies.each do |agency|
        tr
          td.agencies
            = agency.bank.name_with_number
          td.agencies
            = agency.ag_name
          td.agencies
            = agency.ag_number
          td.agencies
            = agency.ag_address
          td
            button.btn.btn-default
              = link_to 'Show', agency
          td
            button.btn.btn-default
              = link_to 'Edit', edit_agency_path(agency)
          td
            button.btn.btn-default
              = link_to 'Delete', agency, :confirm => 'Are you sure?', :method => :delete

app/views/agencies/new.html.slim
h1 style=("font-family: candara;")
  | Register a new agency

== render 'form'

= link_to 'Back', agencies_path

app/views/agencies/show.html.slim
p#notice = notice

p
  b Bank:
  = " #{@agency.bank.name_with_number}"
p
  b Agency Name:
  = " #{@agency.ag_name}"
p
  b Agency Number:
  = " #{@agency.ag_number}"
p
  b Agency Address:
  = " #{@agency.ag_address}"

= link_to 'Edit', edit_agency_path(@agency)
'|
= link_to 'Back', agencies_path