config/routes.rb
Rails.application.routes.draw do
  resources :banks
  resources :agencies
  resources :accounts
  resources :operations

  get 'home/index'
  root to: 'home#index'
  devise_for :users

end

app/views/layouts/application.html.slim
doctype html
html[lan="en"]
  head
    title
      |  SuraBank
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1"]
    meta[name="description" content=""]
    meta[name="author" content=""]

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"]
    script[src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"]
    script[src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"]

  body.app
    - if user_signed_in?
      #wrapper
        #sidebar-wrapper
          ul.sidebar-nav
            li.sidebar-brand
              a[href="#"]
                |  SuraBank
            li
              = link_to 'Home', root_path
            li
              = link_to 'Banks', banks_path
            li
              = link_to 'Agencies', agencies_path
            li
              = link_to 'Accounts', accounts_path
            li
              = link_to 'Transactions', operations_path
            li
              = link_to('Logout', destroy_user_session_path, method: :delete)
        #page-content-wrapper
          div style=("position: relative; bottom: 10px; right: 10px;")
            a#menu-toggle.btn.btn-default[href="#menu-toggle"]
              | <>
          .container-fluid
            .row
              .col-lg-12
                = yield
      script[src="js/jquery.js"]
      script[src="js/bootstrap.min.js"]
      script
        |  $("#menu-toggle").click(function(e) { e.preventDefault(); $("#wrapper").toggleClass("toggled"); });
    - else
      = yield