config/routes.rb
Rails.application.routes.draw do
  resources :banks
  resources :agencies
  resources :accounts
  resources :operations

  get 'home/index'
  root to: 'home#index'
  devise_for :users

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  # Mandatory
  belongs_to :initial_account, :class_name => "Account", :foreign_key => "initial_account_id"

  # Not required if the operation is deposit or withdrawl
  belongs_to :final_account, :class_name => "Account", :foreign_key => "final_account_id"

  enum op_type: {
    deposit: 1,
    withdrawl: 2,
    transfer: 3
  }

  validates_presence_of :initial_account_id, :op_type, :op_value
  validate :check_limit
  validates_presence_of :final_account_id, if: :transfer?
  after_create :update_limit

  def self.enum_capitalizer
    Operation.op_types.to_a.map{|op_type| [op_type.first.capitalize, op_type.first]}
  end

  def check_limit
    if !deposit? && initial_account.present? && (initial_account.acc_limit < op_value)
      errors.add(:op_value, "Insuficient funds in the account.")
    end
  end

  def update_limit
    if deposit?
      initial_account.update(acc_limit: initial_account.acc_limit + op_value)
    end
    if withdrawl?
      initial_account.update(acc_limit: initial_account.acc_limit - op_value)
    end
    if transfer?
      initial_account.update(acc_limit: initial_account.acc_limit - op_value)
      final_account.update(acc_limit: final_account.acc_limit + op_value)
    end
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]
  before_action :set_dependencies, except: [:show]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    def set_dependencies
      @agencies = Agency.all
      @accounts = Account.all
      @operation_types = Operation.enum_capitalizer
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:initial_account_id, :final_account_id, :op_type, :op_value, :op_date)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.slim
= form_for @operation do |f|
  -if @operation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@operation.errors.count, "error")} prohibited this operation from being saved:"
      ul
        - @operation.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label "Sender Account"
    = collection_select :operation, :initial_account_id, @accounts, :id, :acc_number, {include_blank: "Select Option"}
  .field
    = f.label "Receiver Account"
    = collection_select :operation, :final_account_id, @accounts, :id, :acc_number, {include_blank: "Select Option"}
  .field
    = f.label "Type"
    = f.select :op_type, options_for_select(@operation_types), {include_blank: "Select Option"}
  .field
    = f.label "Value"
    = f.text_field :op_value
  .field
    = f.label "Date"
    = f.date_select :op_date
  .actions
    = f.submit 'Save'

app/views/operations/edit.html.slim
h1.operations
  | Editing operation

== render 'form'

= link_to 'Show', @operation
'|
= link_to 'Back', operations_path

app/views/operations/index.html.slim
.operations
  h1.operations
    | Listing previously made operations

  button.btn.btn-dark.btn-lg.active
    = link_to 'Make a new Transaction', new_operation_path

  table.table.table-striped.table-hover
    thead.thead-dark
      tr
        th.operations
          | Sender Agency
        th.operations
          | Sender Account
        th.operations
          | Receiver Agency
        th.operations
          | Receiver Account
        th.operations
          | Type
        th.operations
          | Value
        th.operations
          | Date
        th

    tbody
      - @operations.each do |operation|
        tr
          td.operations
            = operation.initial_account.agency.ag_number
          td.operations
            = operation.initial_account.acc_number
          - if operation.transfer?
            td.operations
              = operation.final_account.agency.ag_number
            td.operations
              = operation.final_account.acc_number
          - else
            td
            td
          td.operations
            = operation.op_type.capitalize
          td.operations
            = operation.op_value
          td.operations
            = operation.op_date
          td
            button.btn.btn-default
              = link_to 'Show', operation

app/views/operations/new.html.slim
h1 New operation

== render 'form'

= link_to 'Back', operations_path

app/views/operations/show.html.slim
p#notice = notice

p
  b Initial Bank Name:
  = @operation.initial_account.agency.bank.name_with_number
br
p
  b Initial Agency Number:
  = @operation.initial_account.agency.ag_number
br
p
  b Initial Account Number:
  = @operation.initial_account.acc_number
br
p
  b Initial Account Balance:
  = @operation.initial_account.acc_limit
br
- if @operation.transfer?
  p
    b Final Bank Name:
    = @operation.final_account.agency.bank.name_with_number
  br
  p
    b Final Agency Number:
    = @operation.final_account.agency.ag_number
  br
  p
    b Final Account Number:
    = @operation.final_account.acc_number
  br
  p
    b Final Account Balance:
    = @operation.final_account.acc_limit
  br

p
  b Operation type:
  = @operation.op_type.capitalize
br
p
  b Operation value:
  = @operation.op_value
br
p
  b Operation date:
  = @operation.op_date

/= link_to 'Edit', edit_operation_path(@operation)
/'|
= link_to 'Back', operations_path